name: Release
on:
  push:
    tags:
    - "*.*.*.*"



jobs:
  publish:
    name: Publish to Jetbrains Marketplace
    runs-on: ubuntu-22.04
    env:
      APP_VERSION: ${{ github.ref_name }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: adopt
          cache: 'gradle'

      - name: Build plugin
        run: sh gradlew buildPlugin --no-daemon
        working-directory: src/intellij

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: src/intellij/build/libs/intellij-${{ env.APP_VERSION }}.jar

      - name: Publish to JetBrains marketplace
        run: sh gradlew publishPlugin --no-daemon
        working-directory: src/intellij
        env:
          JETBRAINS_TOKEN: ${{ secrets.JETBRAINS_TOKEN }}
